name: 자동머지봇
on:
  pull_request:
    types: [labeled]
    branches:
      - main/*
jobs:
  run_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically Merge PR
        uses: plm9606/automerge_actions@1.2.2
        with:
          label-name: '위키-기여'
          reviewers-number: 0
          merge-method: 'merge'
          github-token: ${{ secrets.AUTO_TOKEN }}
